import pandas as pd, matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
plt.close("all")
df=pd.read_parquet("/kaggle/working/cleaned.parquet")
ist=pd.to_datetime(df["created_dt"]).dt.tz_convert("Asia/Kolkata")
daily=ist.dt.date.value_counts().sort_index()
# GUARD: date range matches expectation (Nov-09 2023 .. ~Apr-09 2024)
assert str(daily.index.min())>="2023-11-08" and str(daily.index.max())<="2024-04-10", \
    f"date range drift {daily.index.min()}..{daily.index.max()}"
print("GUARD OK date range:", daily.index.min(), "->", daily.index.max())
fig,ax=plt.subplots(2,1,figsize=(15,10))
s=pd.Series(daily.values,index=pd.to_datetime(list(daily.index)))
s.plot(ax=ax[0],alpha=.4,label="daily"); s.rolling(7).mean().plot(ax=ax[0],lw=2,label="7d rolling")
ax[0].set_title("Daily tickets + 7d rolling mean"); ax[0].legend()
dow=ist.dt.day_name().value_counts().reindex(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
dow.plot.bar(ax=ax[1],title="Tickets by day-of-week"); ax[1].tick_params(rotation=0)
plt.tight_layout(); plt.savefig("/kaggle/working/eda_out/31_calendar.png",dpi=110)
print("saved 31_calendar.png")
print("monthly totals:")
print(ist.dt.to_period("M").value_counts().sort_index().to_string())
print("day-of-week:", dow.to_dict())
