import pandas as pd, numpy as np, matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
plt.close("all")
df=pd.read_parquet("/kaggle/working/cleaned.parquet")
sev=pd.read_parquet("/kaggle/working/derived/severity.parquet")
df=df.merge(sev[["id","sev_sum","max_sev"]],on="id")
df["glat"]=df["latitude"].round(3); df["glon"]=df["longitude"].round(3)
g=df.groupby(["glat","glon"]).agg(n=("id","size"),impact=("sev_sum","sum"),
                                  t3=("max_sev",lambda s:(s>=3).sum())).reset_index()
g=g[g["n"]>=50].copy()
g["rank_count"]=g["n"].rank(ascending=False)
g["rank_impact"]=g["impact"].rank(ascending=False)
g["divergence"]=g["rank_count"]-g["rank_impact"]   # +ve => impact rank BETTER than count rank (under-counted, high-impact)
g.to_parquet("/kaggle/working/derived/divergence.parquet")
print("cells>=50:",len(g),"| corr(count,impact): %.3f"%g["n"].corr(g["impact"]))
print("\nHIGH-IMPACT-but-LOWER-VOLUME cells (impact rank much better than count rank):")
hi=g.sort_values("divergence",ascending=False).head(10)
for _,r in hi.iterrows():
    st=df[(df.glat==r.glat)&(df.glon==r.glon)]["police_station"].mode().iat[0]
    print(f"  ({r.glat:.3f},{r.glon:.3f}) {st:16s} count#{int(r.rank_count):4d} impact#{int(r.rank_impact):4d}  n={int(r.n)} T3={int(r.t3)}")
fig,ax=plt.subplots(1,2,figsize=(15,7))
s0=ax[0].scatter(g.glon,g.glat,c=np.log10(g.n),cmap="inferno",s=10); ax[0].set_title("Volume (log tickets)"); plt.colorbar(s0,ax=ax[0])
s1=ax[1].scatter(g.glon,g.glat,c=np.log10(g.impact),cmap="inferno",s=10); ax[1].set_title("Congestion IMPACT (log severity-sum)"); plt.colorbar(s1,ax=ax[1])
plt.tight_layout(); plt.savefig("/kaggle/working/eda_out/63_severity_density.png",dpi=110)
print("saved 63_severity_density.png")
